gromacs with cdt 20.08 and pat
eth-cscs/production pull request #1943
Opened 2020-09-16 14:47 UTC by sebkelle1

2020-09-18 10:30 UTC, sebkelle1 commented
restest this please

2020-09-18 10:30 UTC, sebkelle1 commented
retest this please

2020-09-25 07:58 UTC, lucamar requested changes
Thanks @sebkelle1, I have added some suggested edits, based on the instructions that I have provided in https://jira.cscs.ch/browse/UES-1134. 
I have also changed `CMake` to the default, which should work as well. Do you really need `craype-accel-nvidia60` as runtime dependency? In general, `cudatoolkit` in `builddependencies` should be enough.

2020-09-25 07:58 UTC, lucamar commented on easybuild/easyconfigs/g/GROMACS/GROMACS-2020.3-CrayGNU-20.08-cuda-pat7.1.1.eb
> +versionsuffix = '-cuda-pat%s' % (local_patversion)
```suggestion
versionsuffix = '-cuda-pat'
```

2020-09-25 07:58 UTC, lucamar commented on easybuild/easyconfigs/g/GROMACS/GROMACS-2020.3-CrayGNU-20.08-cuda-pat7.1.1.eb
> +    ('perftools-lite/%s' % local_patversion, EXTERNAL_MODULE),
```suggestion
    ('CMake', '3.14.5', '', True),
    ('perftools-lite', EXTERNAL_MODULE),
```

2020-09-25 07:58 UTC, lucamar commented on easybuild/easyconfigs/g/GROMACS/GROMACS-2020.3-CrayGNU-20.08-cuda-pat7.1.1.eb
> +    ('cray-libsci', EXTERNAL_MODULE)
```suggestion
    ('craype-accel-nvidia60', EXTERNAL_MODULE),
```

2020-09-25 08:30 UTC, lucamar commented on easybuild/easyconfigs/g/GROMACS/GROMACS-2020.3-CrayGNU-20.08-cuda-pat7.1.1.eb
> +    ('cray-libsci', EXTERNAL_MODULE)
The module `cray-libsci` is loaded by default with `PrgEnv-gnu`, loaded by `CrayGNU`.

2020-09-25 08:45 UTC, lucamar commented
The build failed with the following error message:
```
ERROR: Program '/tmp/jenscscs/ad65d21gpu/GROMACS/2020.3/CrayGNU-20.08-cuda-pat7.1.1/easybuild_obj/share/template/../../bin/template+orig' is already instrumented with PerfToolsWARNING: PerfTools is saving object files from a temporary directory into directory '/users/jenscscs/.craypat/template/12138'
WARNING: the link is executed in a temporary directory which may not be accessible later for pat_build
WARNING: the resulting executable was created in a temporary directory which may not be accessible later for pat_build
INFO: creating the PerfTools-instrumented executable '../../bin/template' (lite-samples) ...FAILED
collect2: error: ld returned 1 exit status
```
See the log file `/scratch/snx3000/jenscscs/TestingEB/daint-gpu/ad65d21-4220/tmp/eb-n2t4aq/easybuild-GROMACS-2020.3-20200918.123940.DHkWU.log`, referenced in https://jenkins.cscs.ch/blue/organizations/jenkins/TestingEB/detail/TestingEB/4220/pipeline.

2020-10-05 10:55 UTC, sebkelle1 commented
addressed all requests that could be satisfied

2020-10-12 08:10 UTC, victorusu approved these changes
`lgtm`

2020-10-12 09:26 UTC, lucamar approved these changes
Thanks @sebkelle1 and @victorusu

2020-10-12 12:56 UTC, merged