[daint] Update jupyterlab-1.2.16-CrayGNU-20.08-batchspawner-cuda.eb
eth-cscs/production pull request #2134
Opened 2021-02-03 11:19 UTC by twrobinson

JupyterHub 1.3 (and deps)  to match change on jupyter VM

2021-02-04 17:45 UTC, omlins requested changes
This should include the changes from #2128

2021-02-05 18:17 UTC, omlins approved these changes

2021-02-05 18:18 UTC, omlins commented
> This should include the changes from #2128

These changes were merged into the master and now pulled into this branch.

2021-02-19 13:31 UTC, twrobinson commented
retest this please

2021-02-19 15:13 UTC, merged