[daint] Add spack-config module
eth-cscs/production pull request #2547
Opened 2021-12-09 15:11 UTC by haampie

2021-12-09 15:45 UTC, haampie commented
@lucamar this module should make https://github.com/eth-cscs/production/tree/master/spack mostly redundant, and a bit more convenient, so you can do `module load spack-config` s.t. the user's spack instance becomes aware of system packages (through en variable + generated config files).

Question I have: what's the naming convention for these files? There's not toolchain required, just git / python. The cdt number is hard-coded. It doesn't work on Eiger, cause that needs `cpe-...` not `cdt-...` apparently.

Also, is this module automatically updated when the cdt version is bumped?

2021-12-09 17:39 UTC, ekouts requested changes

2021-12-09 17:43 UTC, ekouts commented on easybuild/easyconfigs/s/spack-config/spack-config-1.0.eb
> +"""
The double "%%" is required in order to mix template values with your own variables.

2021-12-09 18:42 UTC, haampie commented on easybuild/easyconfigs/s/spack-config/spack-config-1.0.eb
> +"""
Thanks!

2021-12-10 10:20 UTC, ekouts approved these changes

2021-12-10 11:54 UTC, haampie commented
@ekouts am I supposed to open separate prs cause dom does not have 20.10 and daint does not have 21.09?

2021-12-10 11:56 UTC, haampie commented
Or can you show me how to just stick to 1  `eb` file for all the systems? The only variable thing is `cdt-x.y` on dom/daint and `cpe-x.y` on eiger/pilatus.

2021-12-10 12:04 UTC, haampie commented
Hm, I've just created two separate prs then #2548  and #2549

2021-12-10 12:08 UTC, haampie commented
Closing in favor of the other two

2021-12-10 12:08 UTC, closed without merging