[daint] GDAL-3.4.1-CrayGNU-21.09 with depenencies
eth-cscs/production pull request #2678
Opened 2022-02-21 13:24 UTC by gkuhl

Add GDAL and dependencies (expat, GEOS, HDF and libgeotiff) for CrayGNU-21.09.

2022-02-21 13:30 UTC, lucamar commented
Ok to test

2022-02-22 11:05 UTC, kraushm requested changes
Thanks for the PR @gkuhl.

The suggested changes are only to remove hard coded versions and to reuse already built dependencies.

2022-02-22 11:05 UTC, kraushm commented on easybuild/easyconfigs/h/HDF/HDF-4.2.15-CrayGNU-21.09.eb
> +    ('Bison', '3.3.2'),
```suggestion
    ('Bison', '3.8.2'),
```

2022-02-22 11:05 UTC, kraushm commented on easybuild/easyconfigs/h/HDF/HDF-4.2.15-CrayGNU-21.09.eb
> +source_urls = ['https://support.hdfgroup.org/ftp/%(name)s/releases/HDF4.2.15/src']
```suggestion
source_urls = ['https://support.hdfgroup.org/ftp/%(name)s/releases/%(name)s%(version)s/src']
```

2022-02-22 17:09 UTC, kraushm approved these changes
lgtm. Thanks!

2022-02-22 17:22 UTC, merged